"""001-init

Revision ID: 2ca7f40caa42
Revises: 
Create Date: 2025-02-13 20:51:23.569836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2ca7f40caa42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertiser',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertiser_id'), 'advertiser', ['id'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cost_per_impression', sa.Float(), nullable=False),
    sa.Column('cost_per_click', sa.Float(), nullable=False),
    sa.Column('ad_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ad_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impressions_limit', sa.Integer(), nullable=False),
    sa.Column('clicks_limit', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'ALL', name='allgenderenum'), nullable=True),
    sa.Column('age_from', sa.Integer(), nullable=True),
    sa.Column('age_to', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_table('mlscore',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mlscore_id'), 'mlscore', ['id'], unique=False)
    op.create_table('click',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_id'), 'click', ['id'], unique=False)
    op.create_table('impression',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impression_id'), 'impression', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impression_id'), table_name='impression')
    op.drop_table('impression')
    op.drop_index(op.f('ix_click_id'), table_name='click')
    op.drop_table('click')
    op.drop_index(op.f('ix_mlscore_id'), table_name='mlscore')
    op.drop_table('mlscore')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_advertiser_id'), table_name='advertiser')
    op.drop_table('advertiser')
    # ### end Alembic commands ###