"""010-banword-model

Revision ID: 66826adb9a88
Revises: c5a80dc91b50
Create Date: 2025-02-20 21:49:15.687802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66826adb9a88'
down_revision: Union[str, None] = 'c5a80dc91b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banword',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_index(op.f('ix_banword_id'), 'banword', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_banword_id'), table_name='banword')
    op.drop_table('banword')
    # ### end Alembic commands ###