"""007-added-hide-campaign

Revision ID: 6bd65ffa8e15
Revises: 707756a65c78
Create Date: 2025-02-17 18:36:20.993350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6bd65ffa8e15'
down_revision: Union[str, None] = '707756a65c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('hide', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'hide')
    # ### end Alembic commands ###