"""004-added-cost-to-click-impression

Revision ID: 88121941064c
Revises: deb8d9095ae1
Create Date: 2025-02-15 23:51:15.344632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88121941064c'
down_revision: Union[str, None] = 'deb8d9095ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click', sa.Column('cost', sa.Float(), nullable=False))
    op.add_column('impression', sa.Column('cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impression', 'cost')
    op.drop_column('click', 'cost')
    # ### end Alembic commands ###