"""003-added-date-model

Revision ID: deb8d9095ae1
Revises: a26e30c89a4f
Create Date: 2025-02-15 14:15:27.528110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'deb8d9095ae1'
down_revision: Union[str, None] = 'a26e30c89a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_date_id'), 'date', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_date_id'), table_name='date')
    op.drop_table('date')
    # ### end Alembic commands ###