apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: grafanareader
    secureJsonData:
      password: samplepassword
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: false
